{% set name = "xraylarch" %}
{% set version = "2025.1.1" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f05ee76c62c711b6e27dc8020283f46c11346be558dd6c92a650188db660f236

build:
  number: 2
  skip: true  # [py<39]

outputs:
  - name: xraylarch-base
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    build:
      entry_points:
        - larch = larch.apps:run_larch
        - feff6l = larch.apps:run_feff6l
        - feff8l = larch.apps:run_feff8l
        - larch_server = larch.apps:run_larch_server
        - larix = larch.apps:run_larix
        - xasviewer = larch.apps:run_xas_viewer
        - larch_xrf = larch.apps:run_larch_xrf
        - larch_xrd1d = larch.apps:run_larch_xrd1d
        - gse_mapviewer = larch.apps:run_gse_mapviewer
        - epics_xrf = larch.apps:run_epics_xrf
    requirements:
      host:
        - python
        - pip
        - setuptools_scm
      run:
        - python
        - asteval >=1.0.4
        - charset-normalizer
        - dill
        - fabio
        - h5py >=3.2
        - hdf5plugin
        - imageio
        - lmfit >=1.3.1
        - larixite
        - matplotlib-base >=3.5
        - mp-api
        - numdifftools >=0.9.41
        - numexpr >=2.8.7  # [py>38]
        - numpy >=1.23,<2
        - packaging
        - pandas
        - peakutils
        - pillow >=8.3.2
        - pip
        - psutil
        - pycifrw
        - pyfai-base
        - pymatgen >=2024.8.9
        - pyshortcuts >=1.9.5
        - pyyaml
        - requests
        - scikit-image
        - scikit-learn
        - scipy >=1.13
        - silx-base >=0.15.2
        - sqlalchemy >=2.0
        - sqlalchemy-utils
        - termcolor
        - toml
        - uncertainties >=3.2.1
        - xraydb >=4.5.5
    test:
      imports:
        - larch
        - larch.xrd
      #commands:
      #  - pip check
      #requires:
      #  - pip

  - name: xraylarch
    build:
      noarch: generic
    requirements:
      host:
        - python
      run:
        - python
        - silx
        - pyfai
        # wxgui extras_require
        - wxpython >=4.2
        - wxutils >=0.3.0
        - wxmplot >=0.9.57
        # qtgui extras_require
        - pyqt
        - pyqtwebengine
        - pyqtgraph
        # jupyter extras_require
        - jupyter_core >=5.0
        - jupyter_client
        - jupyter_server
        - notebook
        - nbformat
        - ipywidgets
        - plotly
        - py3dmol
        - {{ pin_subpackage('xraylarch-base', max_pin="x.x.x") }}
    test:
      imports:
        - larch
        - larch.xrd
      commands:
        - larch --help
        - feff6l --help
        - feff8l --help
        - larch_server --help
        - larix --help
        - xasviewer --help
        - larch_xrf --help
        # - larch_xrd1d
        - gse_mapviewer --help
        # - epics_xrf

about:
  home: https://xraypy.github.io/xraylarch
  license: MIT
  license_file: LICENSE
  summary: 'Larch: X-ray Analysis for Synchrotron Applications using Python'
  doc_url: https://xraypy.github.io/xraylarch
  dev_url: https://github.com/xraypy/xraylarch

extra:
  recipe-maintainers:
    - maurov
    - mrakitin
    - conda-forge/event-model
